import { createHash } from 'node:crypto'
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { test } from 'node:test'
import assert from 'node:assert/strict'
import {
  buildCoverageDenominators,
  buildCategoryDenominators,
  classifyCoverageEntry,
  COVERAGE_CLASSES,
  DEFAULT_COVERAGE_POLICY,
  deterministicScopeShards,
  inventoryCoverageRecords,
  refreshCategoryDenominators,
} from '../scripts/lib/coverage-model.mjs'
import {
  inventoryRepository,
  serializeInventory,
} from '../scripts/lib/inventory.mjs'

function sha256(value) {
  return createHash('sha256').update(value).digest('hex')
}

function entry(path, size, overrides = {}) {
  return {
    path,
    kind: 'text',
    size,
    sha256: sha256(`${path}:${size}`),
    content: '',
    ...overrides,
  }
}

test('coverage classes and default closure policy are exact and frozen', () => {
  assert.deepEqual(COVERAGE_CLASSES, {
    CANONICAL_SOURCE: 'CANONICAL_SOURCE',
    GENERATED_CODE: 'GENERATED_CODE',
    TEST: 'TEST',
    DOCUMENTATION: 'DOCUMENTATION',
    BINARY: 'BINARY',
  })
  assert.equal(Object.isFrozen(COVERAGE_CLASSES), true)
  assert.deepEqual(DEFAULT_COVERAGE_POLICY, {
    maxFiles: 64,
    maxBytes: 4 * 1024 * 1024,
    maxRounds: 3,
  })
  assert.equal(Object.isFrozen(DEFAULT_COVERAGE_POLICY), true)
})

test('classification applies binary, test, generated, documentation, source precedence', () => {
  const cases = [
    {
      input: entry('tests/generated/readme.md', 4, { kind: 'binary', content: '@generated' }),
      expected: [COVERAGE_CLASSES.BINARY, 'kind:binary'],
    },
    {
      input: entry('tests/generated/client.generated.ts', 4, { content: '@generated' }),
      expected: [COVERAGE_CLASSES.TEST, 'path:test-directory'],
    },
    {
      input: entry('vendor/docs/readme.md', 4),
      expected: [COVERAGE_CLASSES.GENERATED_CODE, 'path:vendor-directory'],
    },
    {
      input: entry('docs/client.ts', 4, { content: '// @generated by sdk' }),
      expected: [COVERAGE_CLASSES.GENERATED_CODE, 'content:generated-marker'],
    },
    {
      input: entry('docs/security.json', 4),
      expected: [COVERAGE_CLASSES.DOCUMENTATION, 'path:documentation-directory'],
    },
    {
      input: entry('README.md', 4),
      expected: [COVERAGE_CLASSES.DOCUMENTATION, 'path:documentation-filename'],
    },
    {
      input: entry('src/order.spec.ts', 4),
      expected: [COVERAGE_CLASSES.TEST, 'path:test-filename'],
    },
    {
      input: entry('force-app/main/default/classes/InvoiceControllerTest.cls', 4),
      expected: [COVERAGE_CLASSES.TEST, 'path:test-filename'],
    },
    {
      input: entry('src/generated/client.ts', 4),
      expected: [COVERAGE_CLASSES.GENERATED_CODE, 'path:generated-directory'],
    },
    {
      input: entry('src/routes/orders.ts', 4),
      expected: [COVERAGE_CLASSES.CANONICAL_SOURCE, 'default:canonical-source'],
    },
  ]

  for (const { input, expected } of cases) {
    const actual = classifyCoverageEntry(input)
    assert.deepEqual(
      [actual.coverage_class, actual.classification_reason],
      expected,
      input.path,
    )
  }
})

test('classification recognizes generated content only in its bounded header', () => {
  const generated = classifyCoverageEntry(entry('src/client.ts', 20, {
    content: `${' '.repeat(16 * 1024 - 32)}// @generated\n`,
  }))
  assert.equal(generated.coverage_class, COVERAGE_CLASSES.GENERATED_CODE)

  const source = classifyCoverageEntry(entry('src/client.ts', 20, {
    content: `${' '.repeat(16 * 1024 + 1)}// @generated\n`,
  }))
  assert.equal(source.coverage_class, COVERAGE_CLASSES.CANONICAL_SOURCE)
})

test('coverage denominators return all five sorted rows with matching files and totals', () => {
  const entries = [
    entry('src/z.ts', 7),
    entry('README.md', 11),
    entry('tests/z.test.ts', 5),
    entry('dist/a.min.js', 13),
    entry('assets/logo.png', 17, { kind: 'binary', content: null }),
    entry('src/a.ts', 3),
  ].map((value) => ({ ...value, ...classifyCoverageEntry(value) }))

  const rows = buildCoverageDenominators({ entries })
  assert.deepEqual(rows, [
    {
      class: COVERAGE_CLASSES.CANONICAL_SOURCE,
      files_total: 2,
      bytes_total: 10,
      files_examined: 0,
      bytes_examined: 0,
      files_unexamined: 2,
      bytes_unexamined: 10,
      paths: ['src/a.ts', 'src/z.ts'],
      files: [{ path: 'src/a.ts', size: 3 }, { path: 'src/z.ts', size: 7 }],
    },
    {
      class: COVERAGE_CLASSES.GENERATED_CODE,
      files_total: 1,
      bytes_total: 13,
      files_examined: 0,
      bytes_examined: 0,
      files_unexamined: 1,
      bytes_unexamined: 13,
      paths: ['dist/a.min.js'],
      files: [{ path: 'dist/a.min.js', size: 13 }],
    },
    {
      class: COVERAGE_CLASSES.TEST,
      files_total: 1,
      bytes_total: 5,
      files_examined: 0,
      bytes_examined: 0,
      files_unexamined: 1,
      bytes_unexamined: 5,
      paths: ['tests/z.test.ts'],
      files: [{ path: 'tests/z.test.ts', size: 5 }],
    },
    {
      class: COVERAGE_CLASSES.DOCUMENTATION,
      files_total: 1,
      bytes_total: 11,
      files_examined: 0,
      bytes_examined: 0,
      files_unexamined: 1,
      bytes_unexamined: 11,
      paths: ['README.md'],
      files: [{ path: 'README.md', size: 11 }],
    },
    {
      class: COVERAGE_CLASSES.BINARY,
      files_total: 1,
      bytes_total: 17,
      files_examined: 0,
      bytes_examined: 0,
      files_unexamined: 1,
      bytes_unexamined: 17,
      paths: ['assets/logo.png'],
      files: [{ path: 'assets/logo.png', size: 17 }],
    },
  ])
  for (const row of rows) {
    assert.equal(row.files_total, row.paths.length)
    assert.deepEqual(row.paths, row.files.map(({ path }) => path))
    assert.equal(
      row.bytes_total,
      row.files.reduce((total, { size }) => total + size, 0),
    )
  }
})

test('typed inventory records drive examined and unexamined counters through compatibility APIs', () => {
  const raw = [
    entry('src/a.ts', 3),
    entry('src/b.ts', 5),
    entry('tests/a.test.ts', 7),
  ].map((value) => ({
    ...value,
    ...classifyCoverageEntry(value),
  }))
  const records = inventoryCoverageRecords(raw)
  assert.deepEqual(
    records.map(({ path, coverage_class: coverageClass, classification_reason: reason }) => ({
      path,
      coverageClass,
      reason,
    })),
    [
      {
        path: 'src/a.ts',
        coverageClass: COVERAGE_CLASSES.CANONICAL_SOURCE,
        reason: 'default:canonical-source',
      },
      {
        path: 'src/b.ts',
        coverageClass: COVERAGE_CLASSES.CANONICAL_SOURCE,
        reason: 'default:canonical-source',
      },
      {
        path: 'tests/a.test.ts',
        coverageClass: COVERAGE_CLASSES.TEST,
        reason: 'path:test-directory',
      },
    ],
  )

  const rows = buildCategoryDenominators(records, ['src/b.ts'])
  const source = rows.find(({ class: coverageClass }) =>
    coverageClass === COVERAGE_CLASSES.CANONICAL_SOURCE)
  assert.deepEqual(source, {
    class: COVERAGE_CLASSES.CANONICAL_SOURCE,
    files_total: 2,
    bytes_total: 8,
    files_examined: 1,
    bytes_examined: 5,
    files_unexamined: 1,
    bytes_unexamined: 3,
    paths: ['src/a.ts', 'src/b.ts'],
    files: [{ path: 'src/a.ts', size: 3 }, { path: 'src/b.ts', size: 5 }],
  })

  const coverage = { inventory_records: records, examined: ['tests/a.test.ts'] }
  refreshCategoryDenominators(coverage)
  const tests = coverage.denominators.find(({ class: coverageClass }) =>
    coverageClass === COVERAGE_CLASSES.TEST)
  assert.deepEqual(
    {
      files_examined: tests.files_examined,
      bytes_examined: tests.bytes_examined,
      files_unexamined: tests.files_unexamined,
      bytes_unexamined: tests.bytes_unexamined,
    },
    {
      files_examined: 1,
      bytes_examined: 7,
      files_unexamined: 0,
      bytes_unexamined: 0,
    },
  )
})

test('v3 schema has one exhaustive typed denominator contract and uncorrupted scope exclusions', async () => {
  const schema = JSON.parse(await readFile(resolve('schemas/run.schema.json'), 'utf8'))
  const coverageProperties = schema.$defs.coverage.properties
  assert.deepEqual(coverageProperties.denominators, {
    $ref: '#/$defs/coverageDenominators',
  })
  assert.deepEqual(
    schema.$defs.coverageDenominators.prefixItems.map(
      (row) => row.allOf[1].properties.class.const,
    ),
    Object.values(COVERAGE_CLASSES),
  )
  assert.deepEqual(
    schema.$defs.coverageDenominator.required,
    [
      'class',
      'files_total',
      'bytes_total',
      'files_examined',
      'bytes_examined',
      'files_unexamined',
      'bytes_unexamined',
      'paths',
      'files',
    ],
  )
  assert.deepEqual(
    Object.keys(schema.$defs.scope.properties.excluded_paths.items.properties),
    ['path', 'reason'],
  )
  assert.deepEqual(
    Object.keys(coverageProperties.gaps.items.properties),
    ['area', 'reason', 'gap_id', 'kind', 'lens', 'path'],
  )
  assert.equal(
    coverageProperties.resolved_gap_ids.items.$ref,
    '#/$defs/coverageGapId',
  )
})

test('deterministic sharding greedily obeys both file and byte bounds', () => {
  const entries = [
    entry('src/d.ts', 4),
    entry('src/a.ts', 3),
    entry('src/c.ts', 2),
    entry('src/b.ts', 5),
    entry('src/e.ts', 0),
  ]
  const shards = deterministicScopeShards(
    ['src/d.ts', 'src/b.ts', 'src/e.ts', 'src/a.ts', 'src/c.ts'],
    entries,
    { maxFiles: 2, maxBytes: 7 },
  )

  assert.deepEqual(
    shards.map(({ index, count, file_count, byte_count, scoped_files }) => ({
      index,
      count,
      file_count,
      byte_count,
      scoped_files,
    })),
    [
      {
        index: 0,
        count: 3,
        file_count: 1,
        byte_count: 3,
        scoped_files: ['src/a.ts'],
      },
      {
        index: 1,
        count: 3,
        file_count: 2,
        byte_count: 7,
        scoped_files: ['src/b.ts', 'src/c.ts'],
      },
      {
        index: 2,
        count: 3,
        file_count: 2,
        byte_count: 4,
        scoped_files: ['src/d.ts', 'src/e.ts'],
      },
    ],
  )
  assert.ok(shards.every(({ scope_sha256 }) => /^[a-f0-9]{64}$/.test(scope_sha256)))
  assert.deepEqual(
    shards.flatMap(({ scoped_files: paths }) => paths),
    ['src/a.ts', 'src/b.ts', 'src/c.ts', 'src/d.ts', 'src/e.ts'],
  )
})

test('shards are stable under inventory and scope permutations', () => {
  const entries = [
    entry('src/a.ts', 2),
    entry('src/b.ts', 3),
    entry('src/c.ts', 4),
    entry('src/d.ts', 5),
  ]
  const first = deterministicScopeShards(
    entries.map(({ path }) => path),
    entries,
    { maxFiles: 2, maxBytes: 7 },
  )
  const second = deterministicScopeShards(
    entries.map(({ path }) => path).reverse(),
    [...entries].reverse(),
    { maxFiles: 2, maxBytes: 7 },
  )
  assert.deepEqual(second, first)
})

test('empty scope produces no shards and defaults use the shared work limit', () => {
  assert.deepEqual(deterministicScopeShards([], []), [])
  const entries = Array.from({ length: 129 }, (_, index) =>
    entry(`src/${String(index).padStart(3, '0')}.ts`, 0))
  const shards = deterministicScopeShards(
    entries.map(({ path }) => path),
    entries,
  )
  assert.deepEqual(shards.map(({ file_count }) => file_count), [64, 64, 1])
})

test('sharding fails closed for invalid limits, ambiguity, and oversized files', () => {
  const entries = [entry('src/a.ts', 8)]
  for (const limits of [
    { maxFiles: 0, maxBytes: 8 },
    { maxFiles: 1, maxBytes: 0 },
    { maxFiles: 1.5, maxBytes: 8 },
    { maxFiles: 1, maxBytes: Number.MAX_SAFE_INTEGER + 1 },
  ]) {
    assert.throws(
      () => deterministicScopeShards(['src/a.ts'], entries, limits),
      /must be an integer between/,
    )
  }
  assert.throws(
    () => deterministicScopeShards(['src/a.ts'], entries, {
      maxFiles: 1,
      maxBytes: 7,
    }),
    /exceeds the 7-byte shard limit/,
  )
  assert.throws(
    () => deterministicScopeShards(['src/a.ts', './src/a.ts'], entries),
    /duplicate paths/,
  )
  assert.throws(
    () => deterministicScopeShards(['src/missing.ts'], entries),
    /absent from inventory/,
  )
  assert.throws(
    () => deterministicScopeShards(['src/a.ts'], [...entries, entries[0]]),
    /inventory contains duplicate path/,
  )
})

test('inventory annotates every entry and binds classification into its tree digest', async () => {
  const root = await mkdtemp(join(tmpdir(), 'red-team-coverage-model-'))
  try {
    await mkdir(join(root, 'src'), { recursive: true })
    await mkdir(join(root, 'tests'), { recursive: true })
    await writeFile(join(root, 'src', 'client.ts'), '// @generated by sdk\n')
    await writeFile(join(root, 'src', 'orders.ts'), 'export const order = 1\n')
    await writeFile(join(root, 'tests', 'orders.test.ts'), 'assert(order)\n')
    await writeFile(join(root, 'logo.bin'), Buffer.from([0, 1, 2, 3]))

    const inventory = await inventoryRepository(root)
    assert.ok(inventory.entries.every(
      ({ coverage_class: coverageClass, classification_reason: reason }) =>
        Object.values(COVERAGE_CLASSES).includes(coverageClass)
        && typeof reason === 'string'
        && reason.length > 0,
    ))
    assert.equal(
      inventory.entries.find(({ path }) => path === 'src/client.ts').coverage_class,
      COVERAGE_CLASSES.GENERATED_CODE,
    )
    assert.equal(
      inventory.entries.find(({ path }) => path === 'tests/orders.test.ts').coverage_class,
      COVERAGE_CLASSES.TEST,
    )
    assert.equal(
      inventory.entries.find(({ path }) => path === 'logo.bin').coverage_class,
      COVERAGE_CLASSES.BINARY,
    )

    const digestInput = inventory.entries.map((value) => [
      value.path,
      value.kind,
      value.size,
      value.sha256 ?? '',
      value.reason ?? '',
      value.category,
      value.coverage_class,
      value.classification_reason,
    ])
    assert.equal(inventory.treeDigest, sha256(JSON.stringify(digestInput)))

    const serialized = serializeInventory(inventory)
    assert.ok(serialized.entries.every(
      (value) => Object.hasOwn(value, 'coverage_class')
        && Object.hasOwn(value, 'classification_reason'),
    ))
  } finally {
    await rm(root, { recursive: true, force: true })
  }
})
