import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { parseLens } from './lib/frontmatter.mjs'
import { isMainModule } from './lib/main-module.mjs'
import { buildRegistry } from './lib/registry.mjs'

const LENS_DIR = 'skills/red-team-audit/lenses'
const TOPICS = join(LENS_DIR, '_topics.md')
const OVERLAP = 'docs/ownership-overlap.md'
const BANNER = '<!-- GENERATED by scripts/gen-topics.mjs — do not edit by hand -->'

export function renderTopics(slugs) {
  const byOwner = new Map()
  for (const [slug, owner] of slugs) {
    if (!byOwner.has(owner)) byOwner.set(owner, [])
    byOwner.get(owner).push(slug)
  }
  const out = ['# Canonical topic registry', '', BANNER, '']
  for (const owner of [...byOwner.keys()].sort()) {
    out.push(`## ${owner}`, '')
    for (const slug of byOwner.get(owner).sort()) out.push(`- ${slug}`)
    out.push('')
  }
  return out.join('\n')
}

export function renderOverlap(lenses, slugs) {
  const deferrers = new Map()
  for (const l of lenses) {
    for (const slug of Object.keys(l.frontmatter.defers ?? {})) {
      if (!deferrers.has(slug)) deferrers.set(slug, [])
      deferrers.get(slug).push(l.frontmatter.name)
    }
  }
  const out = ['# Topic ownership and deferrals', '', BANNER, '', '| Topic slug | Owning lens | Lenses deferring to it |', '|---|---|---|']
  for (const slug of [...slugs.keys()].sort()) {
    const d = (deferrers.get(slug) ?? []).sort()
    out.push(`| \`${slug}\` | ${slugs.get(slug)} | ${d.length ? d.join(', ') : '—'} |`)
  }
  out.push('')
  return out.join('\n')
}

function load() {
  if (!existsSync(LENS_DIR)) {
    console.error(`lens directory not found: ${LENS_DIR}`)
    process.exit(1)
  }
  const lenses = readdirSync(LENS_DIR)
    .filter((f) => f.endsWith('.md') && !f.startsWith('_'))
    .sort()
    .map((f) => parseLens(readFileSync(join(LENS_DIR, f), 'utf8'), f))
  return { lenses, slugs: buildRegistry(lenses).slugs }
}

// Canonical-path comparison keeps this executable through a linked skill
// installation as well as through Windows path/URL spelling differences.
const isDirectRun = isMainModule(import.meta.url)
if (isDirectRun) {
  const check = process.argv.includes('--check')
  const { lenses, slugs } = load()
  const targets = [
    { path: TOPICS, content: renderTopics(slugs) },
    { path: OVERLAP, content: renderOverlap(lenses, slugs) },
  ]
  let drift = false
  for (const { path, content } of targets) {
    if (check) {
      const existing = readFileSync(path, 'utf8')
      if (existing !== content) {
        console.error(`DRIFT: ${path} does not match what frontmatter generates. Run "npm run gen".`)
        drift = true
      }
    } else {
      writeFileSync(path, content)
      console.log(`wrote ${path}`)
    }
  }
  if (drift) process.exit(1)
  if (check) console.log(`PASS: generated artifacts match frontmatter (${slugs.size} slugs).`)
}
