# C-010 — clean fixture. Expected findings at Low or above: ZERO.
#
# This is the fixture ai-generated-code's own false-positive section demands: it
# carries the tells rather than the absence of them. Six shapes that light up the
# lens's §0 sweeps are present on purpose, and none of them is a defect:
#
#   * `except ValueError: pass` around an `int()`            (false positive 2)
#   * `contextlib.suppress(FileNotFoundError)` around unlink  (false positive 2)
#   * `hashlib.md5(..., usedforsecurity=False)` as a cache key (false positive 3)
#   * a lazy Django queryset evaluated AFTER the guard        (false positive 8)
#   * a guard called as a bare statement, which RAISES        (false positive 9)
#   * an anchored allowlist regex that rejects, not rewrites  (false positive 7)
#
# And one shape that lights up web-and-api's injection sweeps: SQL assembled with
# an f-string, `", ".join(...)` and `+`, handed to `cursor.execute`. It reads like
# concatenated user input. It is not.
#
# Why the SQL is not injectable:
#   Two different things are interpolated and they are not the same kind of thing.
#   IDENTIFIERS (column names, sort column) are interpolated, and every one of
#   them is a member of `_EXPORTABLE_COLUMNS`, a frozenset of literals declared in
#   this file — a name that is not in the set raises before the string is built,
#   so the interpolated text is always one of nine hand-written literals.
#   VALUES are never interpolated: `%s` placeholders are generated by count and
#   the parameters are passed as the second argument to `execute`. A column name
#   cannot be bound in SQL — there is no placeholder for a projection or an
#   ORDER BY position — which is why an allowlist is the correct fix here rather
#   than a shortcut around one.

from __future__ import annotations

import contextlib
import hashlib
import logging
import re
from pathlib import Path
from typing import Any, Iterable, Sequence

from django.db import connection

from .models import Invoice

log = logging.getLogger(__name__)

# The projection allowlist. Nine literals, closed, in this file.
_EXPORTABLE_COLUMNS: frozenset[str] = frozenset(
    {
        "id",
        "org_id",
        "invoice_number",
        "status",
        "currency",
        "amount_cents",
        "issued_on",
        "due_on",
        "created_at",
    }
)

# Anchored at BOTH ends, and `\Z` rather than `$` because Python's `$` also
# matches immediately before a trailing newline — so `"...-abc\n"` would pass a
# `$`-anchored pattern. This REJECTS a non-conforming id; it does not strip
# characters and carry on, which is the shape that would be a finding.
_EXPORT_ID = re.compile(
    r"\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\Z"
)

_CACHE_ROOT = Path("/var/cache/billing-exports")

_ALLOWED_STATUSES: frozenset[str] = frozenset({"draft", "open", "paid", "void"})


class ExportPermissionError(PermissionError):
    """Raised — never returned — when the caller may not run this export."""


def require_export_role(user: Any) -> None:
    """Assert the caller holds the export entitlement.

    This function RAISES on failure and returns `None` on success, so calling it
    as a bare statement is the correct call shape: there is no boolean to
    discard. That is the discriminator between this and a predicate whose answer
    nothing consumes.
    """
    if "billing.export" not in user.entitlements:
        raise ExportPermissionError(f"user {user.pk} lacks billing.export")


def cache_key_for(org_id: int, columns: Sequence[str], statuses: Sequence[str]) -> str:
    """Derive a fixed-width filesystem-safe cache key.

    MD5 with `usedforsecurity=False`, which is the author stating the non-security
    intent in the API itself. Nothing is authenticated by this value: a collision
    would serve one report where another was expected, inside a single org's own
    cache directory, and the org id is a separate path segment rather than part of
    the digest input's trust story. Collision resistance is not load-bearing, so
    the broken property has no consequence to name.
    """
    shape = "|".join([str(org_id), ",".join(sorted(columns)), ",".join(sorted(statuses))])
    return hashlib.md5(shape.encode("utf-8"), usedforsecurity=False).hexdigest()


def parse_page_size(raw: str | None, default: int = 500) -> int:
    """Read an optional page size off the query string.

    `except ValueError: pass` with a narrow type on a parse fallback. Naming the
    type IS the review: `int()` raises exactly `ValueError` on a bad string, the
    expected failure is "the caller sent something that is not a number", and the
    handled outcome is the documented default. Nothing security-relevant is
    swallowed — the clamp below runs on every path.
    """
    size = default
    if raw is not None:
        try:
            size = int(raw)
        except ValueError:
            pass
    return max(1, min(size, 5000))


def evict_stale_export(key: str) -> None:
    """Delete a cached export if it is still there.

    `contextlib.suppress(FileNotFoundError)` around an unlink: the file being
    already gone is the same outcome as deleting it, and a concurrent evictor
    winning the race is normal. The suppressed exception is not a control.
    """
    with contextlib.suppress(FileNotFoundError):
        (_CACHE_ROOT / f"{key}.csv").unlink()


def rows_for_export(
    user: Any,
    org_id: int,
    requested_columns: Iterable[str],
    sort_column: str,
    statuses: Iterable[str],
    page_size_raw: str | None,
) -> list[tuple]:
    """Run the export query.

    Reads like string-concatenated SQL. Every interpolated token is a literal
    from `_EXPORTABLE_COLUMNS`; every value is a placeholder.
    """
    require_export_role(user)

    columns = [c for c in requested_columns if c in _EXPORTABLE_COLUMNS]
    if not columns:
        raise ValueError("no exportable columns requested")
    if sort_column not in _EXPORTABLE_COLUMNS:
        raise ValueError(f"cannot sort by {sort_column!r}")

    status_list = [s for s in statuses if s in _ALLOWED_STATUSES]
    if not status_list:
        raise ValueError("no permitted statuses requested")

    limit = parse_page_size(page_size_raw)

    projection = ", ".join(f'"{c}"' for c in columns)
    placeholders = ", ".join(["%s"] * len(status_list))

    sql = (
        f"SELECT {projection} FROM billing_invoice "
        f"WHERE org_id = %s AND status IN ({placeholders}) "
        f'ORDER BY "{sort_column}" DESC LIMIT %s'
    )

    params: list[object] = [org_id, *status_list, limit]

    with connection.cursor() as cursor:
        cursor.execute(sql, params)
        return cursor.fetchall()


def visible_invoice_ids(user: Any, org_id: int, export_id: str) -> list[int]:
    """Return invoice ids for one export, scoped to the caller's org.

    The queryset is CONSTRUCTED before the guard and EVALUATED after it.
    Constructing a Django queryset issues no query and touches no rows, so the
    guard is correctly placed even though it appears below the assignment in
    source order. Evaluation happens at the `list(...)` on the last line, which is
    after `require_export_role` has either returned or raised.
    """
    if not _EXPORT_ID.match(export_id):
        raise ValueError("malformed export id")

    queryset = (
        Invoice.objects.filter(org_id=org_id, export_id=export_id)
        .order_by("-created_at")
        .values_list("id", flat=True)
    )

    require_export_role(user)

    log.info("export %s scoped to org %s", export_id, org_id)
    return list(queryset)
