# C-013 — clean fixture. Expected findings at Low or above: ZERO.
#
# Why this pattern-matches as vulnerable:
#   `verify=False` appears three times. It is one of the highest-confidence
#   literals in the whole corpus — crypto-and-key-management's TLS sweep, its §0
#   sweep and ai-generated-code's A11 all fire on it, and the lens grades a real
#   `verify=False` as Critical.
#
# Why it is not a finding:
#   The discriminator crypto-and-key-management insists on is the HOST LITERAL AT
#   THE CALL SITE, not the directory. So it is written at every call site, three
#   times, and it is a loopback address with a fixed port that the fixture itself
#   starts:
#
#       https://127.0.0.1:4443        (the emulator this module launches)
#
#   The certificate is generated by `local_emulator.start()` into a temp dir at
#   test time and thrown away at teardown, so there is no CA to trust and nothing
#   for a pin to pin. No value here is read from configuration, no environment
#   variable can retarget the host, and there is no import of this module from any
#   non-test path — the file is a pytest module, its only symbols are fixtures and
#   `test_*` functions, and it imports nothing from the application except the
#   client under test.
#
#   What deliberately does NOT appear, because none of it would clear anything:
#   no "it's internal", no "there's a mesh", no "it's behind the VPN", and no
#   `NODE_TLS_REJECT_UNAUTHORIZED` or `urllib3.disable_warnings()` hiding a
#   second, non-local disable elsewhere in the file.
#
# False-positive entries exercised:
#   ai-generated-code (4)          `verify=False` against a local fixture, with
#                                  the host literal at the call site
#   ai-generated-code (13)         a security test's own fixtures, exempted by an
#                                  anchored path — this file is under
#                                  `fixtures/clean/tests/`
#   crypto-and-key-management       the rejected candidate "crypto in a test file
#                                  is never a finding" is deliberately NOT what
#                                  makes this clean; the host literal is

from __future__ import annotations

import pytest
import requests

from . import local_emulator

# Loopback, fixed port, started by this module. Written as a literal so the
# discriminator is at the call site and not in a settings file.
EMULATOR_BASE = "https://127.0.0.1:4443"


@pytest.fixture(scope="module")
def emulator():
    """Start the receipt-validation emulator on loopback with a throwaway cert."""
    handle = local_emulator.start(host="127.0.0.1", port=4443)
    try:
        yield handle
    finally:
        handle.stop()


def test_emulator_accepts_a_well_formed_receipt(emulator):
    # verify=False against https://127.0.0.1:4443 — the emulator's certificate is
    # self-signed and regenerated per run, so there is no trust anchor to install.
    response = requests.post(
        "https://127.0.0.1:4443/v1/receipts",
        json={"receipt": "AAAA", "product": "notes.pro.monthly"},
        timeout=5,
        verify=False,
    )
    assert response.status_code == 200
    assert response.json()["status"] == "valid"


def test_emulator_rejects_a_replayed_receipt(emulator):
    body = {"receipt": "BBBB", "product": "notes.pro.monthly"}

    first = requests.post(
        "https://127.0.0.1:4443/v1/receipts", json=body, timeout=5, verify=False
    )
    assert first.status_code == 200

    replay = requests.post(
        "https://127.0.0.1:4443/v1/receipts", json=body, timeout=5, verify=False
    )
    assert replay.status_code == 409


def test_production_client_does_not_disable_verification():
    """The control test for the file above.

    A test module that turns verification off is only acceptable while the
    shipped client leaves it on, so that is asserted here rather than assumed.
    `requests` defaults `verify` to True; this pins the default against a future
    edit that adds a `verify=` kwarg to the session builder.
    """
    from application.receipts import build_session

    session = build_session(base_url=EMULATOR_BASE)
    assert session.verify is True
    assert session.trust_env is False
